### ISSUE TITLE
ローカルで値の初期化を行っている

### ISSUE THREAD

**Issue by key-moon** [monkukui/procon-qa#79]
questionやanswerの投稿時に、バリデーションや初期値の指定をローカルで行っているため、悪意があるクライアントによって不正な値を入れられてしまう可能性があります。
なので、悪意のある初期値を入れられると困る場所はサーバーサイドで再度初期化すると良いと思います。

![image](https://user-images.githubusercontent.com/32513370/75704892-8ec55600-5cfd-11ea-854b-b5294c70ab68.png)

また、このような悪意のあるケースでなくとも、ローカルでは時差や時刻のズレなどの問題で時刻が合わなくなる可能性があります。サーバーサイドの時刻を使用し、保存時はUnixタイムスタンプとして保存することで、クライアントで表示する際に文字列化するようにすれば時差の問題も解決するかと思います。

**Comment by key-moon** [comment]
これに関連して、サーバーサイドではURLの検証も行うと良いと思います。(スキームが`http://` or `https://`のものだけに限定しないと、`javascript:alert(1)`みたいなのを突っ込まれてXSSの危険性があります。ページを開いて即時に実行されないにせよ、攻撃者のスクリプトをページ上に内包するのはおそらく避けるべきです)

**Comment by monkukui** [comment]
URL の検証というのは，質問の入力欄の一つである URL のことを指しますか？

**Comment by key-moon** [comment]
はい(まさにそのようなことです。)
