### ISSUE TITLE
少し長いタイトルの表示

### ISSUE THREAD

**Issue by uta8a** [monkukui/procon-qa#81]
見た目に関する意見です。

少し長いタイトルは、一覧ではすべてが表示されて、 `/#/question?questionId=xxx` では末尾が `...` と表示されています。表示方法を逆にして、長いタイトルは一覧では縮小して、個別に見るときにすべて表示させるとよい気がします。
細かい指摘ですみません...

![Screenshot from 2020-03-03 15-37-14](https://user-images.githubusercontent.com/31395466/75750370-640fe780-5d67-11ea-978f-3bc60764a126.png)
![Screenshot from 2020-03-03 15-37-26](https://user-images.githubusercontent.com/31395466/75750387-6f631300-5d67-11ea-9d6d-d3ac37a6e713.png)
![Screenshot from 2020-03-03 16-01-37](https://user-images.githubusercontent.com/31395466/75750778-4db65b80-5d68-11ea-8391-665203fd83e1.png)

**Comment by monkukui** [comment]
これはその通りだと思います．
対応します．

**Comment by monkukui** [comment]
ok
