### ISSUE TITLE
提案: 検証用のdocker-composeの導入

### ISSUE THREAD

**Issue by uta8a** [monkukui/procon-qa#82]
バグを探すなど、検証したい人が現れたときにdocker-composeがあると手元での環境構築が簡単になりそうです。
これは提案なので、よさそうであればプルリクを送ります。(不要であればcloseしてください)

以下は一例です
変更例: https://github.com/uta8a/procon-qa/commit/36cf9f961595c1a9341c69e6c51eb613fe4b892e
```
git clone ...
cd procon-qa
docker-compose build
docker-compose up
```
としてからlocalhost:8080にアクセスすると動かせる状態になっています。(元の開発環境を邪魔しないよう、 `env="test"` という形で動かしています)

**Comment by monkukui** [comment]
PR していただけるなら，とてもありがたいです！

**Comment by monkukui** [comment]
マージしました！
